# Generated by Django 3.1.6 on 2021-05-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogblog', '0003_youser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='youId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.youser'),
        ),
    ]
