# Generated by Django 3.1.6 on 2021-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogblog', '0004_item_youid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Codename',
            field=models.TextField(default=''),
        ),
    ]
