# Generated by Django 3.1.6 on 2021-05-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogblog', '0005_item_codename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Codename',
            new_name='CodeId',
        ),
    ]
