# Generated by Django 3.1.6 on 2021-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogblog', '0008_item_feelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descId',
            field=models.TextField(default=''),
        ),
    ]
