# Generated by Django 3.1.6 on 2021-06-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogblog', '0009_item_descid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField(choices=[('Horizontal Window Blinds', 'Horizontal Window Blinds'), ('Vertical Window Blinds', 'Vertical Window Blinds')], default='', null=True)),
                ('Operation', models.TextField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='', null=True)),
                ('Materials', models.TextField(choices=[('Plastic', 'Plastic'), ('Wood', 'Wood'), ('Fabric', 'Fabric')], default='', null=True)),
                ('Design', models.TextField(choices=[('Trilogy Combi Shades', 'Trilogy Combi Shades'), ('Natural Color', 'Natural Color'), ('BlockOut(Monotone)', 'BlockOut(Monotone)'), ('BlockOut(SeeThruCombi)', 'BlockOut(SeeThruCombi)')], default='', null=True)),
                ('Color', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mySelect', models.TextField(choices=[('Cm', 'Cm'), ('Inches', 'Inches'), ('Foot', 'Foot'), ('Meter', 'Meter'), ('Yard', 'Yard'), ('Millimeter', 'Millimeter')], default='', null=True)),
                ('height', models.IntegerField(default='')),
                ('width', models.IntegerField(default='')),
                ('result1', models.IntegerField(default='')),
                ('result2', models.IntegerField(default='')),
                ('size', models.IntegerField(default='')),
                ('lowestAmount', models.IntegerField(default='')),
                ('highestAmount', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(default='')),
                ('MeetUpDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Time', models.TextField(default='')),
                ('contnum', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('deliverydate', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDesign', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.design')),
                ('CInquiry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.inquiry')),
                ('COrder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.order')),
            ],
        ),
        migrations.AddField(
            model_name='youser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='youser',
            name='age',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='youser',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='youser',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='youser',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='youser',
            name='repeat',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='orderslip',
            name='CYouser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.youser'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='IYouser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.youser'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='EYouser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.youser'),
        ),
        migrations.AddField(
            model_name='design',
            name='DYouser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogblog.youser'),
        ),
    ]
